$file = 'c:\xampp\htdocs\motomaster\enginemodule.html'
$content = Get-Content $file -Raw

# Find the lesson-area div start and the closing of lesson-area + bottom bar total
$marker1 = '            <div class="lesson-area" id="lessonArea">'
$marker2 = '<div class="bottom-step-info">Lesson <strong id="currentStepLabel">1</strong> of <strong>7</strong></div>'

$i1 = $content.IndexOf($marker1)
$i2 = $content.IndexOf($marker2)

if ($i1 -lt 0 -or $i2 -lt 0) {
    Write-Error "Markers not found: i1=$i1 i2=$i2"
    exit 1
}

$before = $content.Substring(0, $i1)
$after = $content.Substring($i2 + $marker2.Length)

$new = @'
            <div class="lesson-area" id="lessonArea">

                <div class="lesson-section" id="section-0">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 1 OF 18</div><div class="lesson-title">Introduction</div><div class="lesson-desc">Get an overview of what you will learn — the complete engine oil change process from start to finish.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>Estimated time: 5 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Difficulty: Easy</div></div>
                    <img class="lesson-img" src="images/enginee.png" alt="Introduction">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>What You Will Learn</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Understand why regular oil changes are essential for engine health.</div><div class="step-item"><div class="step-num">2</div>Learn the tools and materials required for a safe oil change.</div><div class="step-item"><div class="step-num">3</div>Follow a 14-step procedure from preparation to disposal.</div></div></div>
                </div>

                <div class="lesson-section" id="section-1">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 2 OF 18</div><div class="lesson-title">Tools &amp; Materials</div><div class="lesson-desc">Gather all necessary tools and materials before starting the engine oil change.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>Estimated time: 5 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Difficulty: Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step1.png" alt="Tools and Materials">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg>Required Tools</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Oil drain pan</div><div class="step-item"><div class="step-num">2</div>Wrench set (14mm/17mm)</div><div class="step-item"><div class="step-num">3</div>New oil filter</div><div class="step-item"><div class="step-num">4</div>Engine oil (correct grade)</div><div class="step-item"><div class="step-num">5</div>Funnel</div><div class="step-item"><div class="step-num">6</div>Gloves and clean rags</div></div></div>
                    <div class="safety-card"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div><div class="safety-title">Safety Reminder</div><div class="safety-desc">Always wear gloves when handling engine oil to protect your skin.</div></div></div>
                </div>

                <div class="lesson-section" id="section-2">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 3 OF 18 — STEP 1</div><div class="lesson-title">Prepare the Vehicle</div><div class="lesson-desc">Park on a flat surface, engage parking brake, turn off engine and allow to cool.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>5 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step1.png" alt="Step 1">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Park on a flat, level surface and engage parking brake.</div><div class="step-item"><div class="step-num">2</div>Turn off engine and allow to cool 10-15 minutes.</div><div class="step-item"><div class="step-num">3</div>Open hood and secure with support rod.</div></div></div>
                    <div class="safety-card"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div><div class="safety-title">Safety Reminder</div><div class="safety-desc">Never work on a hot engine — allow sufficient cooling time.</div></div></div>
                </div>

                <div class="lesson-section" id="section-3">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 4 OF 18 — STEP 2</div><div class="lesson-title">Locate the Drain Plug</div><div class="lesson-desc">Find the oil drain plug at the bottom of the engine oil pan.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>5 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step2.png" alt="Step 2">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Access the underside of the vehicle using jack stands.</div><div class="step-item"><div class="step-num">2</div>Find the oil pan — flat metal pan at the engine bottom.</div><div class="step-item"><div class="step-num">3</div>Identify the drain plug bolt at the lowest point.</div></div></div>
                    <div class="safety-card"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div><div class="safety-title">Safety Reminder</div><div class="safety-desc">Never work under a vehicle supported only by a floor jack.</div></div></div>
                </div>

                <div class="lesson-section" id="section-4">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 5 OF 18 — STEP 3</div><div class="lesson-title">Position the Oil Pan</div><div class="lesson-desc">Place the drain pan correctly to catch all old oil.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>3 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step3.png" alt="Step 3">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Place drain pan directly beneath the drain plug.</div><div class="step-item"><div class="step-num">2</div>Ensure pan can hold 4-5 liters.</div><div class="step-item"><div class="step-num">3</div>Position slightly forward — oil may shoot at an angle.</div></div></div>
                </div>

                <div class="lesson-section" id="section-5">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 6 OF 18 — STEP 4</div><div class="lesson-title">Remove the Drain Plug</div><div class="lesson-desc">Use the correct wrench to remove the drain plug and begin draining.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>5 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step4.png" alt="Step 4">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Select correct wrench size (14mm or 17mm).</div><div class="step-item"><div class="step-num">2</div>Turn counterclockwise to loosen.</div><div class="step-item"><div class="step-num">3</div>Remove fully by hand — keep clear of oil flow.</div><div class="step-item"><div class="step-num">4</div>Set plug aside in a safe, clean location.</div></div></div>
                    <div class="safety-card"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div><div class="safety-title">Safety Reminder</div><div class="safety-desc">Warm oil can splash — wear gloves and keep hands clear.</div></div></div>
                </div>

                <div class="lesson-section" id="section-6">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 7 OF 18 — STEP 5</div><div class="lesson-title">Drain the Old Oil</div><div class="lesson-desc">Allow old oil to fully drain into the pan before filter removal.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>10 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step5.png" alt="Step 5">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Let oil drain completely — 5 to 10 minutes.</div><div class="step-item"><div class="step-num">2</div>Wait until only a slow drip remains.</div><div class="step-item"><div class="step-num">3</div>Inspect drain plug washer — replace if worn.</div></div></div>
                </div>

                <div class="lesson-section" id="section-7">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 8 OF 18 — STEP 6</div><div class="lesson-title">Remove the Old Oil Filter</div><div class="lesson-desc">Remove the old filter while oil is still draining.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>7 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Medium</div></div>
                    <img class="lesson-img" src="images/enginemodule/step6.png" alt="Step 6">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Locate oil filter on side of engine block.</div><div class="step-item"><div class="step-num">2</div>Use oil filter wrench to loosen counterclockwise.</div><div class="step-item"><div class="step-num">3</div>Remove by hand — tilt to avoid spilling.</div></div></div>
                    <div class="safety-card"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div><div class="safety-title">Safety Reminder</div><div class="safety-desc">Old filter contains residual oil — handle carefully.</div></div></div>
                </div>

                <div class="lesson-section" id="section-8">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 9 OF 18 — STEP 7</div><div class="lesson-title">Prepare the New Filter</div><div class="lesson-desc">Apply new oil to the gasket of the new filter to ensure a proper seal.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>3 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step7.png" alt="Step 7">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Unpack the new oil filter.</div><div class="step-item"><div class="step-num">2</div>Apply a thin film of new oil to the rubber gasket ring.</div><div class="step-item"><div class="step-num">3</div>This ensures proper seal and prevents leaks.</div></div></div>
                </div>

                <div class="lesson-section" id="section-9">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 10 OF 18 — STEP 8</div><div class="lesson-title">Install the New Filter</div><div class="lesson-desc">Thread and hand-tighten the new oil filter into place.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>5 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Medium</div></div>
                    <img class="lesson-img" src="images/enginemodule/step8.png" alt="Step 8">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Thread new filter clockwise by hand.</div><div class="step-item"><div class="step-num">2</div>Tighten 3/4 turn after gasket contacts engine.</div><div class="step-item"><div class="step-num">3</div>Hand tight only — do not use a wrench.</div></div></div>
                    <div class="safety-card"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div><div class="safety-title">Safety Reminder</div><div class="safety-desc">Overtightening damages the gasket and causes leaks.</div></div></div>
                </div>

                <div class="lesson-section" id="section-10">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 11 OF 18 — STEP 9</div><div class="lesson-title">Reinstall the Drain Plug</div><div class="lesson-desc">Clean and reinstall the drain plug securely before adding new oil.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>5 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step9.png" alt="Step 9">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Wipe drain plug and area clean.</div><div class="step-item"><div class="step-num">2</div>Install new washer if old one is worn.</div><div class="step-item"><div class="step-num">3</div>Thread plug clockwise by hand, then snug with wrench.</div></div></div>
                    <div class="safety-card"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div><div class="safety-title">Safety Reminder</div><div class="safety-desc">A loose drain plug causes immediate oil leak on start.</div></div></div>
                </div>

                <div class="lesson-section" id="section-11">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 12 OF 18 — STEP 10</div><div class="lesson-title">Locate the Filler Cap</div><div class="lesson-desc">Find the oil filler cap on top of the engine.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>2 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step10.png" alt="Step 10">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Look on top of engine for cap with oil can symbol.</div><div class="step-item"><div class="step-num">2</div>Twist counterclockwise to remove.</div><div class="step-item"><div class="step-num">3</div>Place cap in a clean area.</div></div></div>
                </div>

                <div class="lesson-section" id="section-12">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 13 OF 18 — STEP 11</div><div class="lesson-title">Pour in New Oil</div><div class="lesson-desc">Refill the engine with the correct amount and type of new oil.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>5 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step11.png" alt="Step 11">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Place funnel into filler opening.</div><div class="step-item"><div class="step-num">2</div>Pour specified amount of oil slowly.</div><div class="step-item"><div class="step-num">3</div>Check vehicle manual for correct quantity.</div></div></div>
                    <div class="safety-card"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div><div class="safety-title">Safety Reminder</div><div class="safety-desc">Do not overfill — causes pressure build-up and seal damage.</div></div></div>
                </div>

                <div class="lesson-section" id="section-13">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 14 OF 18 — STEP 12</div><div class="lesson-title">Check Oil Level</div><div class="lesson-desc">Use the dipstick to verify oil level is correct.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>3 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step12.png" alt="Step 12">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Pull dipstick out and wipe clean.</div><div class="step-item"><div class="step-num">2</div>Reinsert fully, then pull out again.</div><div class="step-item"><div class="step-num">3</div>Level should be between MIN and MAX marks.</div><div class="step-item"><div class="step-num">4</div>Add more in small amounts if needed.</div></div></div>
                </div>

                <div class="lesson-section" id="section-14">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 15 OF 18 — STEP 13</div><div class="lesson-title">Replace the Filler Cap</div><div class="lesson-desc">Securely replace the oil filler cap to prevent leaks.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>2 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step13.png" alt="Step 13">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Place filler cap back onto the opening.</div><div class="step-item"><div class="step-num">2</div>Twist clockwise until secure.</div><div class="step-item"><div class="step-num">3</div>Wipe any spilled oil off the engine.</div></div></div>
                </div>

                <div class="lesson-section" id="section-15">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 16 OF 18 — STEP 14</div><div class="lesson-title">Start Engine &amp; Verify</div><div class="lesson-desc">Start the engine, check for leaks, and verify oil pressure.</div></div></div>
                    <div class="meta-row"><div class="meta-tag time"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>5 min</div><div class="meta-tag diff"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>Easy</div></div>
                    <img class="lesson-img" src="images/enginemodule/step14.png" alt="Step 14">
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>Instructions</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Start engine and run for 1-2 minutes.</div><div class="step-item"><div class="step-num">2</div>Check oil pressure light — should turn off in seconds.</div><div class="step-item"><div class="step-num">3</div>Inspect drain plug and filter for leaks.</div><div class="step-item"><div class="step-num">4</div>Turn off, wait 5 min, recheck dipstick level.</div><div class="step-item"><div class="step-num">5</div>Dispose old oil at approved recycling center.</div></div></div>
                    <div class="safety-card"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div><div class="safety-title">Safety Reminder</div><div class="safety-desc">Never pour old oil down the drain — it is hazardous waste.</div></div></div>
                </div>

                <div class="lesson-section" id="section-16">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 17 OF 18</div><div class="lesson-title">Knowledge Check</div><div class="lesson-desc">Test your understanding of the engine oil change procedure.</div></div></div>
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>Quick Quiz</div><div class="step-list"><div class="step-item"><div class="step-num">Q1</div>What should you place under the drain plug before removing it?</div><div class="step-item"><div class="step-num">Q2</div>Why apply oil to the new filter gasket?</div><div class="step-item"><div class="step-num">Q3</div>What tool checks if the oil level is correct?</div><div class="step-item"><div class="step-num">Q4</div>What happens if you overfill?</div><div class="step-item"><div class="step-num">Q5</div>How should you dispose of old engine oil?</div></div></div>
                    <div class="safety-card"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div><div class="safety-title">Tip</div><div class="safety-desc">Review previous sections if unsure of any answers.</div></div></div>
                </div>

                <div class="lesson-section" id="section-17">
                    <div class="lesson-header"><div><div class="lesson-step-label">LESSON 18 OF 18</div><div class="lesson-title">Summary</div><div class="lesson-desc">Review the key takeaways from the Engine Oil Change module.</div></div></div>
                    <div class="steps-card"><div class="steps-card-title"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/></svg>Key Takeaways</div><div class="step-list"><div class="step-item"><div class="step-num">1</div>Always ensure engine is cool before starting.</div><div class="step-item"><div class="step-num">2</div>Replace the oil filter every time.</div><div class="step-item"><div class="step-num">3</div>Use correct oil grade from vehicle manual.</div><div class="step-item"><div class="step-num">4</div>Check oil level with dipstick — between MIN and MAX.</div><div class="step-item"><div class="step-num">5</div>Dispose old oil responsibly at recycling center.</div></div></div>
                    <div class="safety-card" style="background:#f0fdf4;border-color:#bbf7d0;"><svg viewBox="0 0 24 24" fill="none" stroke="#16a34a" stroke-width="2"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/></svg><div><div class="safety-title" style="color:#16a34a;">Module Complete!</div><div class="safety-desc">You have completed all lessons. You are now ready for the practice simulation.</div></div></div>
                </div>

            </div>

            <!-- BOTTOM NAV BAR -->
            <div class="bottom-bar">
                <div class="bottom-step-info">Lesson <strong id="currentStepLabel">1</strong> of <strong>18</strong></div>
'@

$result = $before + $new + $after
[System.IO.File]::WriteAllText($file, $result)
Write-Output "Done - file updated successfully"
