(function () {
    function loadMotoMasterSecurityGuard() {
        if (window.MotoMasterSecurityGuard) {
            window.MotoMasterSecurityGuard.init();
            return;
        }

        if (document.querySelector('script[data-motomaster-security="true"]')) {
            return;
        }

        const guardScript = document.createElement('script');
        guardScript.src = 'js/security-guard.js';
        guardScript.defer = true;
        guardScript.dataset.motomasterSecurity = 'true';
        guardScript.onload = () => window.MotoMasterSecurityGuard && window.MotoMasterSecurityGuard.init();
        document.head.appendChild(guardScript);
    }

    loadMotoMasterSecurityGuard();

    function getTeacherProfile() {
        const stored = localStorage.getItem('motomasterTeacher') || sessionStorage.getItem('motomasterTeacher');
        if (!stored) return null;

        try {
            return JSON.parse(stored);
        } catch (error) {
            return null;
        }
    }

    function fullName(teacher) {
        if (!teacher) return '';
        return [teacher.first_name, teacher.last_name].filter(Boolean).join(' ').trim();
    }

    function setText(id, value) {
        const element = document.getElementById(id);
        if (element && value) element.textContent = value;
    }

    function setValue(id, value) {
        const element = document.getElementById(id);
        if (element && value) element.value = value;
    }

    function applyTeacherProfile() {
        const teacher = getTeacherProfile();
        if (!teacher) return;

        const name = fullName(teacher);
        const role = teacher.role || 'Teacher';
        const dept = teacher.specialization || 'Automotive Technology Dept.';
        const teacherDisplay = name ? `Teacher ${name}` : 'Teacher';

        document.querySelectorAll('.teacher-name, .profile-name, .profile-info-name, .ru-name').forEach((node) => {
            if (name) node.textContent = name;
        });

        document.querySelectorAll('.teacher-role, .profile-role').forEach((node) => {
            if (role) node.textContent = role;
        });

        document.querySelectorAll('.teacher-dept, .profile-info-sub').forEach((node) => {
            if (dept) node.textContent = dept;
        });

        replaceTextAcrossPage('R. Garcia', name);
        replaceTextAcrossPage('Teacher Garcia', teacherDisplay);
        replaceTextAcrossPage('R Garcia', name);
        replaceTextAcrossPage('Welcome back, R. Garcia!', name ? `Welcome back, ${name}!` : 'Welcome back!');
        replaceTextAcrossPage('Good morning, Teacher Garcia!', `Good morning, ${teacherDisplay}!`);
        replaceTextAcrossPage('MotoMaster &bull; R. Garcia &bull; Automotive Technology Dept. &bull; Generated: May 28, 2025', `MotoMaster &bull; ${name || 'Teacher'} &bull; ${dept} &bull; Generated: May 28, 2025`);
        replaceTextAcrossPage('This report was automatically generated by MotoMaster for R. Garcia — Automotive Technology Department. Data reflects all enrolled students across active modules as of the report period. For questions or concerns, contact the department administrator.', `This report was automatically generated by MotoMaster for ${name || 'Teacher'} — ${dept}. Data reflects all enrolled students across active modules as of the report period. For questions or concerns, contact the department administrator.`);

        setValue('profileFirstName', teacher.first_name);
        setValue('profileLastName', teacher.last_name);
        setValue('profileEmail', teacher.email);
        setValue('profileSpecialization', teacher.specialization);
        setValue('profileContact', teacher.contact_number);

        const teacherCards = document.querySelectorAll('[data-teacher-fullname]');
        teacherCards.forEach((node) => {
            node.textContent = name;
        });

        const deptNodes = document.querySelectorAll('[data-teacher-dept]');
        deptNodes.forEach((node) => {
            node.textContent = dept;
        });
    }

    function replaceTextAcrossPage(searchText, replacementText) {
        if (!searchText || !replacementText) return;
        const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
            acceptNode(node) {
                if (!node || !node.parentElement) return NodeFilter.FILTER_REJECT;
                const parentTag = node.parentElement.tagName;
                if (parentTag === 'SCRIPT' || parentTag === 'STYLE' || parentTag === 'TEXTAREA') {
                    return NodeFilter.FILTER_REJECT;
                }
                return node.nodeValue.includes(searchText) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
            }
        });

        const nodes = [];
        while (walker.nextNode()) {
            nodes.push(walker.currentNode);
        }

        nodes.forEach((node) => {
            node.nodeValue = node.nodeValue.split(searchText).join(replacementText);
        });
    }

    function injectDarkThemeStyle() {
        const styleId = 'motomaster-dark-theme-style';
        if (document.getElementById(styleId)) return;

        const css = `
            body.dark-theme,
            body.dark-theme main,
            body.dark-theme .main-content {
                background: #0b0f17 !important;
                color: #f8fafc !important;
            }
            body.dark-theme {
                --bg-color: #0b0f17 !important;
                --border-color: #1e293b !important;
                --text-primary: #f8fafc !important;
                --text-secondary: #94a3b8 !important;
                --accent: #3b82f6 !important;
                --accent-dark: #2563eb !important;
                --accent-light: #1e293b !important;
            }
            body.dark-theme .sidebar,
            body.dark-theme .topbar,
            body.dark-theme .profile-pill,
            body.dark-theme .btn-outline,
            body.dark-theme .settings-nav,
            body.dark-theme .settings-panel,
            body.dark-theme .panel,
            body.dark-theme .kpi-card,
            body.dark-theme .student-card,
            body.dark-theme .assess-card,
            body.dark-theme .practice-card,
            body.dark-theme .report-card,
            body.dark-theme .nm-modal,
            body.dark-theme .filter-tabs,
            body.dark-theme .stat-card,
            body.dark-theme .view-modal,
            body.dark-theme .chat-container,
            body.dark-theme .chat-sidebar,
            body.dark-theme .chat-area,
            body.dark-theme .side-panel,
            body.dark-theme .profile-section,
            body.dark-theme footer {
                background: #1e293b !important;
                color: #f8fafc !important;
                border-color: #1e293b !important;
            }
            body.dark-theme div[style*="background:#fff"],
            body.dark-theme div[style*="background:#ffffff"],
            body.dark-theme div[style*="background: #fff"],
            body.dark-theme div[style*="background: #ffffff"],
            body.dark-theme div[style*="background:white"],
            body.dark-theme div[style*="background: white"],
            body.dark-theme tr[style*="background:#fff"],
            body.dark-theme tr[style*="background:#ffffff"] {
                background: #1e293b !important;
                color: #f8fafc !important;
            }
            body.dark-theme .sidebar {
                background: #0f172a !important;
                border-right-color: #1e293b !important;
            }
            body.dark-theme .logo-container,
            body.dark-theme .logo-text {
                color: #f8fafc !important;
            }
            body.dark-theme .form-control {
                background: #0f172a !important;
                color: #f8fafc !important;
                border-color: #334155 !important;
            }
            body.dark-theme .form-control:focus {
                border-color: #3b82f6 !important;
            }
            body.dark-theme input::placeholder,
            body.dark-theme textarea::placeholder {
                color: #64748b !important;
            }
            body.dark-theme p,
            body.dark-theme h1,
            body.dark-theme h2,
            body.dark-theme h3,
            body.dark-theme h4,
            body.dark-theme h5,
            body.dark-theme h6,
            body.dark-theme span,
            body.dark-theme div,
            body.dark-theme label,
            body.dark-theme td,
            body.dark-theme th {
                color: inherit;
            }
            body.dark-theme *[style*="color:#1a1a2e"],
            body.dark-theme *[style*="color:#111827"],
            body.dark-theme *[style*="color:#1e293b"],
            body.dark-theme *[style*="color:#000000"],
            body.dark-theme *[style*="color:#000"],
            body.dark-theme *[style*="color: #1a1a2e"],
            body.dark-theme *[style*="color: #111827"],
            body.dark-theme *[style*="color: #1e293b"],
            body.dark-theme *[style*="color: #000000"],
            body.dark-theme *[style*="color: #000"] {
                color: #f8fafc !important;
            }
            body.dark-theme .muted,
            body.dark-theme .panel-subtitle,
            body.dark-theme .form-hint,
            body.dark-theme .notif-desc,
            body.dark-theme .notif-time,
            body.dark-theme .notif-meta,
            body.dark-theme .side-label,
            body.dark-theme .kpi-foot span,
            body.dark-theme .teacher-dept {
                color: #94a3b8 !important;
            }
            body.dark-theme .settings-nav-item:hover,
            body.dark-theme .settings-nav-item.active {
                background: #1e293b !important;
                color: #3b82f6 !important;
            }
            body.dark-theme .nav-item {
                color: #94a3b8 !important;
            }
            body.dark-theme .nav-item:hover,
            body.dark-theme .nav-item.active {
                background: #1e293b !important;
                color: #3b82f6 !important;
            }
            body.dark-theme .teacher-card {
                background: #0f172a !important;
                border-color: #1e293b !important;
            }
            body.dark-theme .divider {
                background: #334155 !important;
            }
            body.dark-theme table th {
                background: #0f172a !important;
                color: #f8fafc !important;
                border-bottom-color: #1e293b !important;
            }
            body.dark-theme table td {
                border-bottom-color: #1e293b !important;
                color: #e2e8f0 !important;
            }
            body.dark-theme .badge-green {
                background: #064e3b !important;
                color: #6ee7b7 !important;
            }
            body.dark-theme .badge-red {
                background: #7f1d1d !important;
                color: #fca5a5 !important;
            }
            body.dark-theme .badge-blue {
                background: #1e3a8a !important;
                color: #93c5fd !important;
            }
            body.dark-theme .badge-orange {
                background: #7c2d12 !important;
                color: #fdba74 !important;
            }
            body.dark-theme .badge-purple {
                background: #581c87 !important;
                color: #d8b4fe !important;
            }
            body.dark-theme .notif-item {
                border-bottom-color: #1e293b !important;
            }
            body.dark-theme .notif-item.unread {
                background: #1e293b !important;
            }
            body.dark-theme .notif-item:hover {
                background: #334155 !important;
            }
            body.dark-theme .message-bubble.received {
                background: #334155 !important;
                color: #f8fafc !important;
            }
            body.dark-theme .message-bubble.sent {
                background: #2563eb !important;
                color: #ffffff !important;
            }
        `;

        const style = document.createElement('style');
        style.id = styleId;
        style.textContent = css;
        document.head.appendChild(style);
    }

    function applyGlobalTheme() {
        injectDarkThemeStyle();
        const theme = localStorage.getItem('motomasterTheme') || 'light';
        if (theme === 'dark') {
            document.body.classList.add('dark-theme');
        } else {
            document.body.classList.remove('dark-theme');
        }
    }

    applyGlobalTheme();

    document.addEventListener('DOMContentLoaded', () => {
        try {
            applyTeacherProfile();
        } catch (e) {
            console.error('Error applying profile:', e);
        }
        try {
            applyGlobalTheme();
        } catch (e) {
            console.error('Error applying theme:', e);
        }
    });
    window.addEventListener('pageshow', () => {
        try {
            applyTeacherProfile();
        } catch (e) {
            console.error('Error applying profile:', e);
        }
        try {
            applyGlobalTheme();
        } catch (e) {
            console.error('Error applying theme:', e);
        }
    });
})();
